name = "SecureComputation"
uuid = "1a59a1ac-80e1-11e9-1c65-07cde08caba7"
authors = ["Jiahao Chen <1732+jiahao@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Polynomials", "Test"]
